alert_work/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('consumer.urls'))
]

api/urls.py
from django.urls import path
from .views import ApiUsers, ApiUser,ApiTasks,ApiTask

app_name = 'api'

urlpatterns = [
    path('users/', ApiUsers.as_view(), name='api_users'),
    path('users/<int:pk>', ApiUser.as_view(), name='api_user'),
    path('task/', ApiTasks.as_view(), name='api-tasks'),
    path('task/<int:pk>', ApiTask.as_view(), name='api-task'),
]

consumer/urls.py
from django.urls import path, include
from .views import LoginView, DetailUser, LogoutView, RegisterView, create_task
from .views import update_task, delete_task, detail_task

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('detail_user/<int:pk>/', DetailUser.as_view(), name='detail_user'),
    path('create_task/', create_task, name='create_task'),
    path('update_task/<int:pk>', update_task, name='update_task'),
    path('delete_task/<int:pk>', delete_task, name='delete_task'),
    path('detail_task/<int:pk>/', detail_task, name='detail_task'),
]

consumer/models.py
from django.db import models

# Create your models here.

consumer/forms.py
from django import forms
from api.models import User, Task
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Username',
                               max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Enter Your username'}))
    password = forms.CharField(label='Password',
                               max_length=30,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control',
                                            'placeholder': 'Enter Your password'}))

class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Username',
                               max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Enter Your username'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(
                                 attrs={'class': 'form-control',
                                        'placeholder': 'Enter your email'}))
    first_name = forms.CharField(label='First Name',
                                 max_length=30,
                                 widget=forms.TextInput(
                                        attrs={'class': 'form-control',
                                               'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(label='Last Name',
                                 max_length=30,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control',
                                            'placeholder': 'Enter your last name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CreateTask(forms.ModelForm):
    title = forms.CharField(label='Title',
                            max_length=30,
                            widget=forms.TextInput(
                                attrs={'class': 'form-control',
                                        'placeholder': 'Enter your title'}))
    description = forms.CharField(label='Description',
                                  max_length=30,
                                  widget=forms.Textarea(
                                        attrs={'class': 'form-control',
                                                  'placeholder': 'Enter your description'}))
    end_date = forms.DateField(label='End Date',
                               widget=forms.DateInput(
                                      attrs={'class': 'form-control input-element',
                                                'placeholder': 'YYYY-MM-DD'}))
    class Meta:
        model = Task
        fields = ('title', 'description', 'end_date')

consumer/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView, DetailView
from django.views.generic import RedirectView, CreateView
from .forms import LoginForm, RegisterForm, CreateTask
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
#from django.shortcuts import get_object_or_404
from api.models import User, Task
from django.contrib.auth.mixins import LoginRequiredMixin
import requests
from django.contrib.auth.decorators import login_required
from datetime import datetime
from utils.scrapper import get_scrapp

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'consumer/login.html'
    success_url = reverse_lazy('users:detail_user')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('users:detail_user', kwargs={'pk': self.request.user.pk})


class DetailUser(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'consumer/detail_user.html'

    def get_context_data(self, **kwargs):
        context = super(DetailUser, self).get_context_data(**kwargs)
        user = requests.get(
            f'http://localhost:8000/api/users/{self.request.user.id}')
        obj = user.json()
        tasks = user.json()['task_user']
        context['user'] = obj
        context['tasks'] = tasks
        context['scrapp'] = get_scrapp()
        return context


class LogoutView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class RegisterView(CreateView):
    form_class = RegisterForm
    model = User
    template_name = 'consumer/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.save()
        return super(RegisterView, self).form_valid(form)


@login_required
def create_task(request):
    tasks = requests.get('http://localhost:8000/api/task')
    if request.method == 'POST':
        form = CreateTask(request.POST)
        title = request.POST['title']
        description = request.POST['description']
        end_date = request.POST['end_date']
        user_id = request.user.id
        id_task = len(tasks.json()['Tasks']) + 1
        data = {
            "id": id_task,
            "title": f"{title}",
            "description": f"{description}",
            "init_date": f"{datetime.today().strftime('%Y-%m-%d')}",
            "end_date": f"{end_date}",
            "user": user_id
        }
        requests.post(
            f'http://localhost:8000/api/task/', data=data)
        return redirect(reverse_lazy('users:detail_user', kwargs={'pk': request.user.pk}))
    else:
        form = CreateTask()

    return render(request, 'consumer/create_task.html', {'form': form})

@login_required
def update_task(request, pk):
    if request.method == 'POST':
        task = requests.get('http://localhost:8000/api/task/' + str(pk))
        form = CreateTask(request.POST)
        title = request.POST['title']
        description = request.POST['description']
        end_date = request.POST['end_date']
        user_id = request.user.id
        task_id = task.json()['id']
        data = {
            "id": task_id,
            "title": f"{title}",
            "description": f"{description}",
            "init_date": f"{datetime.today().strftime('%Y-%m-%d')}",
            "end_date": f"{end_date}",
            "user": user_id
        }
        requests.put(
            f'http://localhost:8000/api/task/{task_id}', data=data)
        return redirect(reverse_lazy('users:detail_user', kwargs={'pk': request.user.pk}))
    else:
        form = CreateTask(instance=task)
    return render(request, 'consumer/update_task.html', {'form': form})

@login_required
def delete_task(request, pk):
    task = requests.get('http://localhost:8000/api/task/' + str(pk))
    task_id = task.json()['id']
    requests.delete(f'http://localhost:8000/api/task/{task_id}')
    return redirect(reverse_lazy('users:detail_user', kwargs={'pk': request.user.pk}))


@login_required
def detail_task(request, pk):
    task = requests.get(
        f'http://localhost:8000/api/task/{pk}')
    return render(request, 'consumer/detail_task.html', {'task': task.json(), 'user': request.user})

templates/consumer/create_task.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <h1 class="text-center mt-4">Add Task</h1>
    <form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success mt-2 button">Create</button>
</form>
</div>

{% endblock %}
{% block js %}
<script>

let cleave = new Cleave('.input-element', {
    date: true,
    delimiter: '-',
    datePattern: ['Y', 'm', 'd']
});


</script>
{% endblock %}

templates/consumer/delete_task.html
{% extends 'base.html' %}
{% block content%}
<h1>{{task.title}}</h1>
<h2>{{task.description}}</h2>
{% endblock %}

templates/consumer/detail_task.html
{% extends 'base.html' %}

{% block content%}
{% include 'consumer/navbar.html' %}
<a href="{% url 'users:detail_user' user.id %}" class="btn btn-danger">Back</a>
<article class="card mx-auto mt-5" style="height:400px; width:400px">
        <div class="card__content">
            <div class="card__date"> {{task.end_date}}
            </div>
            <div class="card__info d-grid" style="place-items: center; height: 400px">
                <h1>{{task.title}}</h1>
                <h4>{{task.description}}</h4>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'users:update_task' task.id %}" class="btn btn-info">Update</a>
                    <a href="{% url 'users:delete_task' task.id %}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </article>

{% endblock %}

templates/consumer/detail_user.html
{% extends 'base.html' %}
{% block title %} {{user.username|capfirst}} {% endblock %} 
{% load static %}
{% block content%}
{% include 'consumer/navbar.html' %}
<div class="container">
    <h1 class="text-center mt-3 mb-5">Welcome {{user.username}}</h1>
</div>
{% if tasks %}
<div id="task"></div>
<div class="gallery ms-5">
    {% for task in tasks %}
    <article class="card mx-auto">
        <div class="card__content">
            <div class="card__date"> {{task.end_date}}
            </div>
            <div class="card__info d-grid" style="place-items: center;">
                <h3>{{task.title}}</h3>
                <a href="{% url 'users:detail_task' task.id %}" class="btn btn-success">Show all</a>
                <div>
                    <a href="{% url 'users:update_task' task.id %}" class="btn btn-info">Update</a>
                    <a href="{% url 'users:delete_task' task.id %}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </article>
    {% endfor %}
</div>
{% else %}
<h3 class="text-center mb-5">Sample Tasks</h3>
<div class="gallery ms-5">
    {% for task in scrapp %}
    <article class="card mx-auto">
        <div class="card__content">
            <div class="card__date"> 2022-04-30
            </div>
            <div class="card__info d-grid" style="place-items: center;">
                <h3>{{task.title}}</h3>
            </div>
        </div>
    </article>
    {% endfor %}
</div>
{% endif %}
{% endblock %}
{% block js %}
    <script>
        function logout(e) {
            var logout = confirm("Are you sure you want to continue?");
            console.log(logout)
            if (logout) {
                return true;
            } else {
                e.preventDefault();
                return false;
            }
        }
        document.querySelectorAll('.btn-danger').forEach((el) => {
            el.addEventListener('click', logout)
        });
    </script>
{% endblock %}

templates/consumer/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}


{% block content %}
    <div class="container mt-5 mb-4 p-5 rounded-3 col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 col-xxl-6" id="form-login">
        <h1 class="text-center">Welcome new user</h1>
        {% load crispy_forms_tags %}
        <form action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-success w-25 mt-4">Login</button>
                <a href="{% url 'users:register' %}"class="btn btn-primary w-25 mt-4">Register</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/consumer/navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <div class="d-flex align-items-center gap-4">
        <h1 class="navbar-brand">{{user.username|capfirst}}</h1>
    </div>
    <div class="navbar-nav d-flex flex-row gap-3">
        <a href="{% url 'users:logout' %}" class="btn btn-danger">Logout</a>
        <a href="{% url 'users:create_task' %}" class="btn btn-primary">Add Task</a>
    </div>
  </div>
</nav>

templates/consumer/register.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}


{% block content %}
    <div class="container mt-5 mb-4 p-5 rounded-3 width_custom col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 col-xxl-6" id="form-login">
        <h1 class="text-center">Welcome new user</h1>
        {% load crispy_forms_tags %}
        <form action="{% url 'users:register' %}" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-success w-25 mt-4">Register</button>
                <a href="{% url 'users:login' %}"class="btn btn-primary w-25 mt-4">Login</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/consumer/update_task.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <h1 class="text-center mt-4">Update Task</h1>
    <form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success mt-2 button">Create</button>
</form>
</div>

{% endblock %}
{% block js %}
<script>

let cleave = new Cleave('.input-element', {
    date: true,
    delimiter: '-',
    datePattern: ['Y', 'm', 'd']
});


</script>
{% endblock %}